FROM node:20-alpine AS builder

WORKDIR /build

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .
RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN npm install -g http-server

COPY --from=builder /build/dist/frontend ./dist

EXPOSE 80

CMD ["http-server", "dist/browser", "-p", "80", "--gzip", "-c-1", "--proxy", "http://localhost:80?"]
